# actions-runner-system / org-runners.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: org-runners
  namespace: actions-runner-system
spec:
  replicas: 1
  template:
    spec:
      organization: anderson-organization
      labels:
        - self-hosted
        - Linux
        - X64
